export const UI_TEXT = {
  CLOTHING_TITLE: "CLOTHING",
  ACCESSORIES_TITLE: "ACCESSORIES",
  TECHNOLOGY_TITLE: "TECHNOLOGY",
  CATEGORIES_TITLE: "CATEGORIES",
  NEW_LABEL: "NEW",
  BUY_NOW: "Buy Now",
  ALL_CLOTHES_UNISEX: "All clothes are Unisex",
};
